#!/usr/bin/env bash

declare -a apps=(

# Basic utilities
bat
file
less
htop
neofetch
ncdu
grep
sed
nnn
git
tree

# Editors
nano
vim
nvim

# Terminal Utilities
ssh
mosh
tmux

# Shells / Scripting utilities
zsh
pv
jq
yq
yj
rlwrap

# Compilers / Build Tools
gcc
make
go
cargo
jsonnet
jsonnet-lint
protoc

# Interpreters / REPLs
yaegi
node
#deno

# Networking utilities
curl
wget
nc
bmon
arp-scan

# Database utilities
mycli
pgcli

# Compression utilities
gzip
gunzip
zip
unzip
bzip2
bunzip2
lz4
xz
zstd

# Crypto utilities
sha256sum
sha3sum

# Kubernetes
kubectl
k9s
helm

# Kafka
kcl

)

function check_app() {
  appName=$1
  if ! which $appName > /dev/null 2>&1; then
    echo "warning: $appName is not installed"
  fi
}

for i in "${apps[@]}"; do
  check_app $i
done
